prompt --application/pages/page_00011
begin
--   Manifest
--     PAGE: 00011
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2023.10.31'
,p_release=>'23.2.5'
,p_default_workspace_id=>1389747021320061
,p_default_application_id=>107
,p_default_id_offset=>776066518237927778
,p_default_owner=>'EXT'
);
wwv_flow_imp_page.create_page(
 p_id=>11
,p_name=>'List Hak Akses'
,p_alias=>'LIST-HAK-AKSES'
,p_page_mode=>'MODAL'
,p_step_title=>'List Hak Akses'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'21'
,p_last_updated_by=>'YEREMIA.NDAUMANU@LIMAMAIL.NET'
,p_last_upd_yyyymmddhh24miss=>'20260115093301'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1512643833385135656)
,p_plug_name=>'List Hak Akses'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(1512195688984912037)
,p_plug_display_sequence=>30
,p_query_type=>'TABLE'
,p_query_table=>'APX_BF_ACCESS_RIGHTS_LISTS'
,p_query_where=>'apx_access_rights_id = :p11_set_apx_access_rights_id'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IG'
,p_prn_page_header=>'List Hak Akses'
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(1512599256618077298)
,p_name=>'APEX$ROW_ACTION'
,p_item_type=>'NATIVE_ROW_ACTION'
,p_display_sequence=>20
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(1512599360587077299)
,p_name=>'APEX$ROW_SELECTOR'
,p_session_state_data_type=>'VARCHAR2'
,p_item_type=>'NATIVE_ROW_SELECTOR'
,p_display_sequence=>10
,p_attribute_01=>'Y'
,p_attribute_02=>'Y'
,p_attribute_03=>'N'
,p_use_as_row_header=>false
,p_required_patch=>wwv_flow_imp.id(1512101675756911678)
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(1512645173711135742)
,p_name=>'ID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ID'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>true
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>30
,p_attribute_01=>'Y'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_is_primary_key=>true
,p_include_in_export=>false
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(1512646098017135760)
,p_name=>'APX_ACCESS_RIGHTS_ID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'APX_ACCESS_RIGHTS_ID'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Apx Access Rights Id'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>40
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'left'
,p_attribute_04=>'decimal'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P11_SET_APX_ACCESS_RIGHTS_ID'
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(1512647085675135761)
,p_name=>'DEPT_NAME'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DEPT_NAME'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_POPUP_LOV'
,p_heading=>'Dept Name'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>50
,p_value_alignment=>'LEFT'
,p_attribute_01=>'POPUP'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_03=>'N'
,p_attribute_04=>'N'
,p_attribute_05=>'N'
,p_is_required=>false
,p_max_length=>4000
,p_lov_type=>'SQL_QUERY'
,p_lov_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select distinct dept_name from APX_BF_BUDGET_MONITOR_HDR ',
'WHERE DEPT_NAME NOT IN (SELECT DEPT_NAME ',
'FROM APX_BF_ACCESS_RIGHTS_LISTS WHERE apx_access_rights_id = :p11_set_apx_access_rights_id)',
'',
'UNION ',
'',
'SELECT ''ADM'' AS dept_name FROM DUAL',
'',
'UNION ',
'',
'SELECT ''INV'' AS dept_name FROM DUAL'))
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_interactive_grid(
 p_id=>wwv_flow_imp.id(1512644371011135675)
,p_internal_uid=>143242341557184105
,p_is_editable=>true
,p_edit_operations=>'i:u:d'
,p_lost_update_check_type=>'VALUES'
,p_add_row_if_empty=>true
,p_submit_checked_rows=>false
,p_lazy_loading=>false
,p_requires_filter=>false
,p_select_first_row=>true
,p_fixed_row_height=>true
,p_pagination_type=>'SCROLL'
,p_show_total_row_count=>true
,p_show_toolbar=>true
,p_enable_save_public_report=>false
,p_enable_subscriptions=>true
,p_enable_flashback=>true
,p_define_chart_view=>true
,p_enable_download=>true
,p_enable_mail_download=>true
,p_fixed_header=>'PAGE'
,p_show_icon_view=>false
,p_show_detail_view=>false
);
wwv_flow_imp_page.create_ig_report(
 p_id=>wwv_flow_imp.id(1512644821021135686)
,p_interactive_grid_id=>wwv_flow_imp.id(1512644371011135675)
,p_static_id=>'1432428'
,p_type=>'PRIMARY'
,p_default_view=>'GRID'
,p_show_row_number=>false
,p_settings_area_expanded=>true
);
wwv_flow_imp_page.create_ig_report_view(
 p_id=>wwv_flow_imp.id(1512644966568135700)
,p_report_id=>wwv_flow_imp.id(1512644821021135686)
,p_view_type=>'GRID'
,p_stretch_columns=>true
,p_srv_exclude_null_values=>false
,p_srv_only_display_columns=>true
,p_edit_mode=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(1512645455776135755)
,p_view_id=>wwv_flow_imp.id(1512644966568135700)
,p_display_seq=>2
,p_column_id=>wwv_flow_imp.id(1512645173711135742)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(1512646496868135760)
,p_view_id=>wwv_flow_imp.id(1512644966568135700)
,p_display_seq=>3
,p_column_id=>wwv_flow_imp.id(1512646098017135760)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(1512647503225135761)
,p_view_id=>wwv_flow_imp.id(1512644966568135700)
,p_display_seq=>4
,p_column_id=>wwv_flow_imp.id(1512647085675135761)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(1512650024332153168)
,p_view_id=>wwv_flow_imp.id(1512644966568135700)
,p_display_seq=>1
,p_column_id=>wwv_flow_imp.id(1512599256618077298)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1512599643216077302)
,p_name=>'P11_SET_APX_ACCESS_RIGHTS_ID'
,p_item_sequence=>10
,p_display_as=>'NATIVE_HIDDEN'
,p_attribute_01=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1512599814743077303)
,p_name=>'P11_SET_APX_ACCESS_RIGHTS_TITLE'
,p_item_sequence=>20
,p_item_default=>'SELECT TITLE FROM APX_bf_ACCESS_RIGHTS WHERE ID = :P11_SET_APX_ACCESS_RIGHTS_ID'
,p_item_default_type=>'SQL_QUERY'
,p_prompt=>'Title'
,p_display_as=>'NATIVE_DISPLAY_ONLY'
,p_field_template=>wwv_flow_imp.id(1512276161722912126)
,p_item_template_options=>'#DEFAULT#'
,p_attribute_01=>'Y'
,p_attribute_02=>'VALUE'
,p_attribute_04=>'Y'
,p_attribute_05=>'PLAIN'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(1512599473212077300)
,p_process_sequence=>10
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_imp.id(1512643833385135656)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'List Hak Akses - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>143197443758125730
);
wwv_flow_imp.component_end;
end;
/
