prompt --application/pages/page_00001
begin
--   Manifest
--     PAGE: 00001
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2023.10.31'
,p_release=>'23.2.5'
,p_default_workspace_id=>1389747021320061
,p_default_application_id=>107
,p_default_id_offset=>776066518237927778
,p_default_owner=>'EXT'
);
wwv_flow_imp_page.create_page(
 p_id=>1
,p_name=>'Home'
,p_alias=>'HOME'
,p_step_title=>'BRIEFCASE EXTENSION'
,p_autocomplete_on_off=>'OFF'
,p_html_page_header=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!-- <div id="loading-progress" style="',
'    position: fixed;',
'    top: 0;',
'    left: 0;',
'    width: 100%;',
'    height: 3px;',
'    background: rgba(255,255,255,0.1);',
'    z-index: 9999;',
'    display: none;',
'">',
'',
'<div id="progress-bar" style="',
'    height: 100%;',
'    background: linear-gradient(90deg, #915EFF, #00dbde);',
'    width: 0%;',
'    transition: width 0.3s ease;',
'"></div>',
'',
'<div id="progress-text" style="',
'    position: absolute;',
'    top: 10px;',
'    right: 20px;',
'    color: #fff;',
'    font-family: Arial, sans-serif;',
'    font-size: 14px;',
'    ">0%</div>',
'</div> -->',
'',
'<!-- ---------------------------------------------------------- -->',
'',
'<!-- <div id="loaderOverlay" class="loader-overlay hidden">',
'    <div class="loader"></div>',
'</div> -->',
'',
'<!-- ---------------------------------------------------------- -->',
'',
'<div id="loaderOverlay" class="loader-overlay hidden">',
'    <div class="loader"></div>',
'    <div class="loader-text" id="loaderPercentage">0%</div>',
'    <div class="loader-progress">',
'        <div class="loader-progress-bar" id="loaderProgressBar"></div>',
'    </div>',
'</div>'))
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'// Loading Progress System',
'function initLoadingProgress() {',
'    const progressBar = document.getElementById(''progress-bar'');',
'    const progressText = document.getElementById(''progress-text'');',
'    const loadingProgress = document.getElementById(''loading-progress'');',
'    ',
'    let progress = 0;',
'    let simulatedProgress = 0;',
'    ',
'    loadingProgress.style.display = ''block'';',
'    ',
'    function simulateLoading() {',
'        const interval = setInterval(() => {',
'            if (progress >= 90) {',
'                clearInterval(interval);',
'                return;',
'            }',
'            ',
'            const increment = Math.random() * 10 + 5;',
'            simulatedProgress = Math.min(progress + increment, 90);',
'            ',
'            updateProgress(simulatedProgress);',
'        }, 200);',
'    }',
'    ',
'    function updateProgress(value) {',
'        progress = value;',
'        progressBar.style.width = progress + ''%'';',
'        progressText.textContent = Math.round(progress) + ''%'';',
'    }',
'    ',
'    window.addEventListener(''load'', function() {',
'        setTimeout(() => {',
'            updateProgress(100);',
'            ',
'            setTimeout(() => {',
'                loadingProgress.style.display = ''none'';',
'            }, 500);',
'        }, 300);',
'    });',
'    ',
'    if (document.readyState === ''loading'') {',
'        document.addEventListener(''DOMContentLoaded'', function() {',
'            updateProgress(30);',
'            simulateLoading();',
'        });',
'    } else {',
'        updateProgress(50);',
'        simulateLoading();',
'    }',
'    ',
'    setTimeout(() => {',
'        if (progress < 100) {',
'            updateProgress(100);',
'            setTimeout(() => {',
'                loadingProgress.style.display = ''none'';',
'            }, 500);',
'        }',
'    }, 5000);',
'}',
'',
'// ----------------------------------------------------------------------------------',
'',
'// function showLoader() {',
'//     const loader = document.getElementById(''loaderOverlay'');',
'//     if (loader) {',
'//         loader.classList.remove(''hidden'');',
'        ',
'//         setTimeout(() => {',
'//             hideLoader();',
'//             apex.server.process(''HIDE_LOADER'');',
'//         }, 3000);',
'//     }',
'// }',
'',
'// function hideLoader() {',
'//     const loader = document.getElementById(''loaderOverlay'');',
'//     if (loader) {',
'//         loader.classList.add(''hidden'');',
'//     }',
'// }',
'',
'// ----------------------------------------------------------------------------------',
'',
'function showLoader() {',
'    const loader = document.getElementById(''loaderOverlay'');',
'    if (loader) {',
'        loader.classList.remove(''hidden'');',
'        ',
'        updateProgress(0);',
'        ',
'        let progress = 0;',
'        const interval = setInterval(() => {',
'            // progress += Math.random() * 15;',
'            progress += Math.random() * 10 + 5;',
'',
'            if (progress > 100) {',
'                progress = 100;',
'                clearInterval(interval);',
'            }',
'            ',
'            updateProgress(Math.round(progress));',
'        }, 300);',
'        ',
'        setTimeout(() => {',
'            hideLoader();',
'            clearInterval(interval);',
'            apex.server.process(''HIDE_LOADER'');',
'        }, 3000);',
'    }',
'}',
'',
'function hideLoader() {',
'    const loader = document.getElementById(''loaderOverlay'');',
'    if (loader) {',
'        loader.classList.add(''hidden'');',
'    }',
'}',
'',
'function updateProgress(percentage) {',
'    const percentageElement = document.getElementById(''loaderPercentage'');',
'    const progressBar = document.getElementById(''loaderProgressBar'');',
'    ',
'    if (percentageElement && progressBar) {',
'        percentageElement.textContent = percentage + ''%'';',
'        progressBar.style.width = percentage + ''%'';',
'    }',
'}'))
,p_javascript_code_onload=>wwv_flow_string.join(wwv_flow_t_varchar2(
'initLoadingProgress();',
'if (apex.item(''P1_SHOW_LOADER'').getValue() === ''Y'') {',
'    showLoader();',
'}',
'',
'apex.item(''P1_SHOW_LOADER'').setValue(''N'');',
'',
'// ------------------------------------------------------------------------',
'',
'// const loaderHTML = `',
'// <div id="loaderOverlay" class="loader-overlay">',
'//     <div class="loader"></div>',
'// </div>',
'// `;',
'',
'// document.body.insertAdjacentHTML(''afterbegin'', loaderHTML);',
'',
'// setTimeout(() => {',
'//     const loader = document.getElementById(''loaderOverlay'');',
'//     if (loader) {',
'//         loader.remove();',
'//     }',
'// }, 3000);',
'',
'// ------------------------------------------------------------------------',
'',
'// const loaderHTML = `',
'// <div id="loaderOverlay" class="loader-overlay">',
'//     <div class="loader"></div>',
'//     <div class="loader-text" id="loaderPercentage">0%</div>',
'//     <div class="loader-progress">',
'//         <div class="loader-progress-bar" id="loaderProgressBar"></div>',
'//     </div>',
'// </div>',
'// `;',
'',
'// document.body.insertAdjacentHTML(''afterbegin'', loaderHTML);',
'',
'// const progressStages = [',
'//     { delay: 300, progress: 20, text: "Memuat konfigurasi..." },',
'//     { delay: 600, progress: 45, text: "Menyiapkan data..." },',
'//     { delay: 900, progress: 70, text: "Memuat antarmuka..." },',
'//     { delay: 1200, progress: 85, text: "Menyelesaikan..." },',
'//     { delay: 2000, progress: 100, text: "Selesai!" }',
'// ];',
'',
'// let currentStage = 0;',
'// const percentageElement = document.getElementById(''loaderPercentage'');',
'// const progressBar = document.getElementById(''loaderProgressBar'');',
'',
'// function advanceProgress() {',
'//     if (currentStage < progressStages.length) {',
'//         const stage = progressStages[currentStage];',
'        ',
'//         setTimeout(() => {',
'//             if (percentageElement && progressBar) {',
'//                 percentageElement.textContent = stage.progress + ''%'';',
'//                 progressBar.style.width = stage.progress + ''%'';',
'                ',
'//                 percentageElement.textContent = stage.text + '' '' + stage.progress + ''%'';',
'//             }',
'//             currentStage++;',
'//             advanceProgress();',
'//         }, stage.delay);',
'//     }',
'// }',
'',
'// advanceProgress();',
'',
'// setTimeout(() => {',
'//     const loader = document.getElementById(''loaderOverlay'');',
'//     if (loader) {',
'//         loader.remove();',
'//     }',
'// }, 5000);',
'',
'// ------------------------------------------------------------------------',
'',
'const loaderHTML = `',
'<div id="loaderOverlay" class="loader-overlay">',
'    <div class="loader"></div>',
'    <div class="loader-text" id="loaderPercentage">0%</div>',
'    <div class="loader-progress">',
'        <div class="loader-progress-bar" id="loaderProgressBar"></div>',
'    </div>',
'</div>',
'`;',
'',
'document.body.insertAdjacentHTML(''afterbegin'', loaderHTML);',
'',
'function updateProgress(percentage, text = "") {',
'    const percentageElement = document.getElementById(''loaderPercentage'');',
'    const progressBar = document.getElementById(''loaderProgressBar'');',
'    ',
'    if (percentageElement && progressBar) {',
'        const displayText = text ? `${text} ${percentage}%` : `${percentage}%`;',
'        percentageElement.textContent = displayText;',
'        progressBar.style.width = percentage + ''%'';',
'    }',
'}',
'',
'let progress = 0;',
'const maxProgress = 90;',
'',
'updateProgress(10, "Memulai...");',
'',
'document.addEventListener(''DOMContentLoaded'', function() {',
'    updateProgress(40, "Konten dimuat...");',
'});',
'',
'window.addEventListener(''load'', function() {',
'    // updateProgress(80, "Resource dimuat...");',
'    updateProgress(80, "Tunggu sebentar yaa...");',
'    ',
'    setTimeout(() => {',
'        updateProgress(100, "Selesai!");',
'        ',
'        setTimeout(() => {',
'            const loader = document.getElementById(''loaderOverlay'');',
'            if (loader) {',
'                loader.style.opacity = ''0'';',
'                loader.style.transition = ''opacity 0.5s ease'';',
'                ',
'                setTimeout(() => {',
'                    loader.remove();',
'                }, 500);',
'            }',
'        }, 300);',
'    }, 300);',
'});',
'',
'setTimeout(() => {',
'    const loader = document.getElementById(''loaderOverlay'');',
'    if (loader && loader.parentNode) {',
'        updateProgress(100, "Selesai!");',
'        ',
'        setTimeout(() => {',
'            loader.style.opacity = ''0'';',
'            loader.style.transition = ''opacity 0.5s ease'';',
'            ',
'            setTimeout(() => {',
'                loader.remove();',
'            }, 500);',
'        }, 300);',
'    }',
'}, 4000);'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* Loading Progress Styles */',
'/* #loading-progress {',
'    position: fixed;',
'    top: 0;',
'    left: 0;',
'    width: 100%;',
'    height: 3px;',
'    background: rgba(255, 255, 255, 0.1);',
'    z-index: 9999;',
'    display: none;',
'}',
'',
'#progress-bar {',
'    height: 100%;',
'    background: linear-gradient(90deg, #915EFF, #00dbde);',
'    width: 0%;',
'    transition: width 0.3s ease;',
'    position: relative;',
'}',
'',
'#progress-text {',
'    position: absolute;',
'    top: 10px;',
'    right: 20px;',
'    color: #fff;',
'    font-family: Arial, sans-serif;',
'    font-size: 14px;',
'    font-weight: bold;',
'    text-shadow: 0 1px 2px rgba(0,0,0,0.5);',
'}',
'',
'#progress-bar.pulse {',
'    animation: pulse 1.5s ease-in-out infinite;',
'}',
'',
'@keyframes pulse {',
'    0% { opacity: 1; }',
'    50% { opacity: 0.7; }',
'    100% { opacity: 1; }',
'} */',
'',
'/* -------------------------------------------------------------------------------------------- */',
'',
'.loader-overlay {',
'    position: fixed;',
'    top: 0;',
'    left: 0;',
'    width: 100%;',
'    height: 100%;',
'    /* background: rgba(255, 255, 255, 0.9); */',
'    /* background: rgba(49, 49, 49, 0.781); */',
'    background: rgba(24, 24, 24, 0.781);',
'    display: flex;',
'    justify-content: center;',
'    align-items: center;',
'    z-index: 9999;',
'    transition: opacity 0.5s ease;',
'',
'    backdrop-filter: blur(10px);',
'    border: 1px solid rgba(255, 255, 255, 0.2);',
'    /* border-radius: 15px; */',
'    box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);',
'    overflow: hidden;',
'}',
'',
'.loader {',
'    transform: rotateZ(45deg);',
'    perspective: 1000px;',
'    border-radius: 50%;',
'    /* width: 48px; */',
'    /* height: 48px; */',
'    width: 72px;',
'    height: 72px;',
'    /* color: #007bff; */',
'    color: #915EFF;',
'    z-index: 9999;',
'}',
'.loader:before,',
'.loader:after {',
'    content: '''';',
'    display: block;',
'    position: absolute;',
'    top: 0;',
'    left: 0;',
'    width: inherit;',
'    height: inherit;',
'    border-radius: 50%;',
'    transform: rotateX(70deg);',
'    animation: 1s spin linear infinite;',
'}',
'.loader:after {',
'    /* color: #FF3D00; */',
'    color: #00dbde;',
'    transform: rotateY(70deg);',
'    animation-delay: .4s;',
'}',
'',
'.loader-text {',
'    font-family: Arial, sans-serif;',
'    font-size: 16px;',
'    font-weight: bold;',
'    background: linear-gradient(90deg, #915EFF, #00dbde);',
'    -webkit-background-clip: text;',
'    -webkit-text-fill-color: transparent;',
'    background-clip: text;',
'    text-align: center;',
'}',
'',
'.loader-progress {',
'    width: 200px;',
'    height: 4px;',
'    background: rgba(255, 255, 255, 0.1);',
'    border-radius: 2px;',
'    margin-top: 10px;',
'    overflow: hidden;',
'}',
'',
'.loader-progress-bar {',
'    height: 100%;',
'    background: linear-gradient(90deg, #915EFF, #00dbde);',
'    border-radius: 2px;',
'    width: 0%;',
'    transition: width 0.3s ease;',
'}',
'',
'@keyframes spin {',
'    0%,',
'    100% {',
'        box-shadow: .2em 0px 0 0px currentcolor;',
'    }',
'    12% {',
'        box-shadow: .2em .2em 0 0 currentcolor;',
'    }',
'    25% {',
'        box-shadow: 0 .2em 0 0px currentcolor;',
'    }',
'    37% {',
'        box-shadow: -.2em .2em 0 0 currentcolor;',
'    }',
'    50% {',
'        box-shadow: -.2em 0 0 0 currentcolor;',
'    }',
'    62% {',
'        box-shadow: -.2em -.2em 0 0 currentcolor;',
'    }',
'    75% {',
'        box-shadow: 0px -.2em 0 0 currentcolor;',
'    }',
'    87% {',
'        box-shadow: .2em -.2em 0 0 currentcolor;',
'    }',
'}',
'',
'.hidden {',
'    display: none !important;',
'}',
'',
'/* -------------------------------------------------------------------------------------------- */'))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'13'
,p_last_updated_by=>'MANUEL'
,p_last_upd_yyyymmddhh24miss=>'20251209144940'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1371749917656661980)
,p_plug_name=>'Page Navigation'
,p_region_name=>'page_navigation'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#:u-colors:t-Cards--featured t-Cards--block force-fa-lg:t-Cards--displayIcons:t-Cards--cols:t-Cards--hideBody:t-Cards--animRaiseCard'
,p_plug_template=>wwv_flow_imp.id(1512138909167912005)
,p_plug_display_sequence=>10
,p_list_id=>wwv_flow_imp.id(1383303308449501966)
,p_plug_source_type=>'NATIVE_LIST'
,p_list_template_id=>wwv_flow_imp.id(1512254476315912098)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1512402631076913186)
,p_plug_name=>'BRIEFCASE EXTENSION'
,p_region_template_options=>'#DEFAULT#'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_imp.id(1512172199212912024)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_plug_query_num_rows=>15
,p_region_image=>'#APP_FILES#icons/app-icon-512.png'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
,p_attribute_03=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1371750148422661983)
,p_name=>'P1_SHOW_LOADER'
,p_item_sequence=>20
,p_display_as=>'NATIVE_HIDDEN'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(1371750318094661984)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'HIDE_LOADER'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'    apex_util.set_session_state(''P9999_SHOW_LOADER'', ''N'');',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>595683799856734206
);
wwv_flow_imp.component_end;
end;
/
