prompt --application/deployment/definition
begin
--   Manifest
--     INSTALL: 101
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>1468196320002782
,p_default_application_id=>101
,p_default_id_offset=>11904843373585791
,p_default_owner=>'EXT'
);
wwv_flow_imp_shared.create_install(
 p_id=>wwv_flow_imp.id(765866099150177820)
,p_deinstall_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- Hapus package body & package spec',
'DROP PACKAGE BODY "APX_BF_USER_MGMT_PKG";',
'DROP PACKAGE "APX_BF_USER_MGMT_PKG";',
'',
'-- Hapus stored procedure & function',
'DROP PROCEDURE create_apex_user;',
'DROP PROCEDURE USER_SYNC_PROC;',
'DROP FUNCTION generate_random_password;',
'DROP FUNCTION get_user_role;',
'',
'-- Hapus view',
'DROP VIEW "APX_BF_ACTIVITY_MASTER_V";',
'DROP VIEW "APX_BF_BUDGET_MONITOR_HDR_V";',
'DROP VIEW "APX_BF_BUDGET_MONITOR_LNS_V";',
'DROP VIEW "APX_BF_COMM_ACT_SUM_V";',
'DROP VIEW "APX_BF_REVENUE_COGS_AMT_V";',
'',
'-- Hapus sequence',
'DROP SEQUENCE "APX_BF_ACTIVITY_INTERFACE_SEQ";',
'DROP SEQUENCE "APX_BUDGET_ENTRY_FULL_TBL_BATCH_ID_SEQ";',
'',
'-- Hapus synonym',
'DROP SYNONYM "XTD_BRF_BUDGET_MKT_MOTR_V";',
'',
'-- Hapus foreign key constraints',
'ALTER TABLE "APX_BF_BUDGET_ALLOCATE" DROP CONSTRAINT "APX_BF_BUDGET_ALLOCATE_FK";',
'ALTER TABLE "APX_BF_BUDGET_ENTRY_LNS" DROP CONSTRAINT "APX_BF_BUDGET_ENTRY_LNS_CON";',
'',
'-- Hapus primary key constraints',
'ALTER TABLE "APX_BF_USER_DEPT_ACCESS" DROP CONSTRAINT "APX_BF_USER_DEPT_ACCESS_PK";',
'ALTER TABLE "APX_BF_USER_COMP_ACCESS" DROP CONSTRAINT "APX_BF_USER_COMP_ACCESS_PK";',
'ALTER TABLE "APX_BF_USER" DROP CONSTRAINT "APX_BF_USER_PK";',
'ALTER TABLE "APX_BF_REVENUE_COGS_AMT" DROP PRIMARY KEY;',
'ALTER TABLE "APX_BF_COMM_ACT_AMT_STG" DROP PRIMARY KEY;',
'ALTER TABLE "APX_BF_COMM_ACT_AMT" DROP PRIMARY KEY;',
'ALTER TABLE "APX_BF_PASSWORD_RESET" DROP PRIMARY KEY;',
'ALTER TABLE "APX_BF_BUDGET_ENTRY_LNS" DROP CONSTRAINT "APX_BF_BUDGET_ENTRY_LNS_PK";',
'ALTER TABLE "APX_BF_BUDGET_ENTRY_HDR" DROP CONSTRAINT "APX_BF_BUDGET_ENTRY_HDR_PK";',
'ALTER TABLE "APX_BF_BUDGET_ALLOCATE" DROP CONSTRAINT "APX_BF_BUDGET_ALLOCATE_PK";',
'ALTER TABLE "APX_BF_USER_ACCESS" DROP CONSTRAINT "APX_BF_USER_ACCESS_ID_PK";',
'ALTER TABLE "APX_BF_HR_DEPARTMENT" DROP CONSTRAINT "APX_BF_HR_DEPARTMENT_ID_PK";',
'ALTER TABLE "APX_BF_ACCESS_RIGHTS_LISTS" DROP CONSTRAINT "APX_BF_ACCESS_RIGHTS_LISTS_ID_PK";',
'ALTER TABLE "APX_BF_ACCESS_RIGHTS" DROP CONSTRAINT "APX_BF_ACCESS_RIGHTS_ID_PK";',
'ALTER TABLE "APX_BF_ACCESS_RIGHTS_INTERFACE" DROP PRIMARY KEY;',
'',
'-- Hapus tabel',
'DROP TABLE "APX_BUDGET_ENTRY_FULL_TBL";',
'DROP TABLE "APX_BF_USER_DEPT_ACCESS";',
'DROP TABLE "APX_BF_USER_COMP_ACCESS";',
'DROP TABLE "APX_BF_USER_ACCESS";',
'DROP TABLE "APX_BF_USER";',
'DROP TABLE "APX_BF_REVENUE_COGS_AMT";',
'DROP TABLE "APX_BF_PASSWORD_RESET";',
'DROP TABLE "APX_BF_HR_DEPARTMENT";',
'DROP TABLE "APX_BF_COMM_ACT_AMT_STG";',
'DROP TABLE "APX_BF_COMM_ACT_AMT";',
'DROP TABLE "APX_BF_BUDGET_ENTRY_LNS";',
'DROP TABLE "APX_BF_BUDGET_ENTRY_HDR";',
'DROP TABLE "APX_BF_BUDGET_ALLOCATE";',
'DROP TABLE "APX_BF_ACTIVITY";',
'DROP TABLE "APX_BF_ACCESS_RIGHTS_LISTS";',
'DROP TABLE "APX_BF_ACCESS_RIGHTS";',
'DROP TABLE "APX_BF_ACCESS_RIGHTS_INTERFACE";',
'DROP TABLE "APX_BF_BUDGET_MONITOR_HDR";',
'DROP TABLE "APX_BF_BUDGET_MONITOR_LNS";',
'DROP TABLE "APX_BF_BUDGET_MONITOR_MKT_HDR";'))
);
wwv_flow_imp.component_end;
end;
/
